### ISSUE TITLE
panic during interface conversion

### ISSUE THREAD

**Issue by zx9597446** [teh-cmc/goautosocket#4]
panic: interface conversion: error is *os.SyscallError, not syscall.Errno

goroutine 66 [running]:
panic(0x170380, 0xc8201aea40)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/teh-cmc/goautosocket.(*TCPClient).Read(0xc82009aa80, 0xc8200e6e00, 0x200, 0x200, 0x0, 0x0, 0x0)
        /Users/cm/go/src/github.com/teh-cmc/goautosocket/tcp_client.go:193 +0x23f
bytes.(*Buffer).ReadFrom(0xc8200e0700, 0x392028, 0xc82009aa80, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.6.2/libexec/src/bytes/buffer.go:176 +0x23f
io.copyBuffer(0x392000, 0xc8200e0700, 0x392028, 0xc82009aa80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.6.2/libexec/src/io/io.go:374 +0x180
io.Copy(0x392000, 0xc8200e0700, 0x392028, 0xc82009aa80, 0xc82009aa80, 0x0, 0x0)
        /usr/local/Cellar/go/1.6.2/libexec/src/io/io.go:350 +0x64
main.runOneConnection.func1(0x357630, 0xc82009aa80)
        /Users/cm/go/src/github.com/zx9597446/tcptest/main.go:58 +0xdd
created by main.runOneConnection
        /Users/cm/go/src/github.com/zx9597446/tcptest/main.go:61 +0xb7

**Comment by georgerb** [comment]
+1

**Comment by dahankzter** [comment]
I have seen this once. The fix would be to just exhaust the possible error types to make sure it is handled appropriately?
